# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BodyBankEnterpriseDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BodyBankEnterpriseDemo
  pod 'BodyBankEnterprise', git: 'github:skonb/BodyBankSDK'

  target 'BodyBankEnterpriseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BodyBankEnterpriseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
